#!/usr/bin/env bash
set -u

# Generated by wildfire_data/generate_missing_progress_runner.py.
# Runs missing task/algorithm/seed combinations from a progress CSV.
MODEL=ernie
URL=http://localhost:8000/v1

GPU_IDS=(4 5 6 7)
NUM_GPUS=${#GPU_IDS[@]}
MAX_JOBS=10
SLEEP_SECONDS=5

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$SCRIPT_DIR/experiment_logs/${MODEL}"

mkdir -p "$LOG_DIR"
cd "$SCRIPT_DIR"

run_job () {
  local model=$1
  local preset=$2
  local seed=$3
  local algo=$4
  local gpu_id=$5
  
  local log_file="$LOG_DIR/${algo}/${preset}/seed${seed}.log"
  local status=0

  mkdir -p "$(dirname "$log_file")"

  echo "Starting: $algo | model=$model | $preset | seed=$seed | GPU=$gpu_id | log=$log_file"

  {
    echo "Starting: $algo | model=$model | $preset | seed=$seed | GPU=$gpu_id"
    echo "Log file: $log_file"
    echo

    CUDA_VISIBLE_DEVICES=$gpu_id SDL_VIDEODRIVER=dummy \
    python -m crew_algorithms.wildfire_alg.algorithms.NOOP \
      envs.level=$preset \
      envs.seed=$seed \
      envs.collaboration_mode=ai_control \
      envs.llm_model=$model \
      envs.llm_url=$URL \
      envs.no_graphics=true

    status=$?
    echo

    if (( status == 0 )); then
      echo "Finished: $algo | model=$model | $preset | seed=$seed"
    else
      echo "Failed: $algo | model=$model | $preset | seed=$seed | exit=$status"
    fi
  } > "$log_file" 2>&1

  return "$status"
}

JOBS=(
  # 'ernie|DARPA_500|42|NOOP'
  # 'ernie|DARPA_stress|42|NOOP'
  'ernie|DARPA_stress_2|42|NOOP'
)

echo "Queued ${#JOBS[@]} missing experiments."

job_count=0
job_id=0

for job in "${JOBS[@]}"; do
  [[ -z "$job" || "$job" == \#* ]] && continue

  IFS="|" read -r model preset seed algo <<< "$job"
  gpu_id=${GPU_IDS[$(( job_id % NUM_GPUS ))]}
  ((job_id++))

  run_job "$model" "$preset" "$seed" "$algo" "$gpu_id" &
  ((job_count++))

  sleep "$SLEEP_SECONDS"

  if (( job_count >= MAX_JOBS )); then
    wait -n
    ((job_count--))
  fi
done

wait

echo "All missing experiments completed."
